### PR TITLE
feat(images): add support for custom docker images

### LINKED ISSUE #255: Feature request: Start nodes with local docker images
Hello!
I think it would be great for developers to be able to define which image will be used for a node, apart from the predefined ones you already use. This way, we could even test modifications in the lnd itself (I am trying to use a forked lnd version and face difficulties changing the docker image used)
Thank you for the useful project!

### PR DESCRIPTION
**Pull request by jamaljsr**
Closes #255, #288 

### Description

This PR adds the ability to create custom nodes which use a specified docker image other than the ones managed in the polarlightning Docker Hub repo. It also adds the ability to customize the docker startup command for both custom and managed nodes. You can customize the commands globally for all future nodes, or for a specific node in an existing network.

There is a new Manage Nodes screen where you can create, edit & delete your custom nodes. You can also alter the default command for all Polar managed nodes. When creating a new network, you can specify how many custom nodes you want to add. Once a network is created, you can also edit the startup command used by each node individually.

I still need to add a bunch more unit tests, but all of the functionality is there. I just want to get this feature out to get feedback from from those that requested it. Please let me know if this solves your use cases @arvchristos & @torkelrogstad.

### Steps to Test

Build a custom image for one of the supported implementations. For LND master branch, follow the steps in [this gist](https://gist.github.com/jamaljsr/f7fe765a0f7a51d4333adc570cf6b3cd). Docs for other implementations will be completed before the next release.

1. Click on Manage Nodes in the navbar menu
1. Click on the Add Custom Node button
1. Fill in the form choosing lnd:master for the Docker Image and click Save
1. Click on Create Network in the navbar menu
1. Enter 1 for the number of your custom node and click Create Network
1. Click on the first node and confirm the sidebar Info tab displays your custom docker image name
1. Start the network
1. Open a terminal for the first node
1. Enter `lncli getinfo` to confirm the version the latest LND commit hash

### Screenshots

image

There are many more screenshots collapsed below. I hid them to avoid the pain of scrolling 
<details>
<summary>View more screenshots</summary>

Add a new custom node
image

Edit a managed node's command
image

Create a new Network with custom nodes
image

Custom nodes are displayed in the designer sidebar
image

New Advanced Options button in the Actions tab
image

Edit the command of an existing node
image

</details>

### CODE REVIEW

**Comment by torkelrogstad** [comment]
Really great stuff! Works great for me. 

Some thoughts on UX: 
* Should it be possible to change the docker command for the default nodes? Kind of makes the difference between custom and managed nodes less clear. 
* Would be great with functionality for defining names of nodes, especially ones using a custom image. 

Don't know if this is related to this PR, but when changing the backend of one of my nodes (not the custom one), I got this error: 

image

**Comment by jamaljsr** [comment]
Hey @torkelrogstad thanks for the feedback.

> Should it be possible to change the docker command for the default nodes? Kind of makes the difference between custom and managed nodes less clear.

My reasoning for adding this for default nodes is that there may be some devs that do not want to go through the hassle of creating a new docker image. They just want to customize the command line flags of the daemon. For example, with the new release of LND v0.9.0, they added the `--accept-keysend` argument. Even though, we can make this release available via a new docker image, we can only modify the command line args by creating a new version of Polar. With the ability to customize the command for these nodes, these users can easily just update the args themselves for any future releases.

>  Would be great with functionality for defining names of nodes, especially ones using a custom image.

There is a name field for custom nodes. Or are you talking about changing the "alice, bob, ..." auto-generated names?

> Don't know if this is related to this PR, but when changing the backend of one of my nodes (not the custom one), I got this error:

I have occasionally seen that issue myself and I think I know what the problem is. I am going to fix that in a separate PR.

**Comment by torkelrogstad** [comment]
The argument on arguments for default images makes sense!

> There is a name field for custom nodes. Or are you talking about changing the "alice, bob, ..." auto-generated names?

Yes, that's what I meant.

**Comment by jamaljsr** [comment]
@torkelrogstad This can be done, but I need just a bit more clarification. Are you saying to add the ability to edit the list of 26 pre-defined node names in [names.ts](https://github.com/jamaljsr/polar/blob/master/src/utils/names.ts)? Or do you want to just be able to rename an individual node after the network is created?

**Comment by torkelrogstad** [comment]
I'm thinking of renaming individual nodes. After the network is created works fine.

**Comment by jamaljsr** [comment]
Ok, sounds good. I can add this feature. I'll do it in a separate PR since this one is already pretty heavy.

**Pull request merged**
