### PR TITLE
feat(images): add support for Bitcoin Core v22.0

### PR DESCRIPTION
**Pull request by cstenglein**
This adds the already existing v22.0  from [Docker Hub](https://hub.docker.com/layers/polarlightning/bitcoind/22.0/images/sha256-54ff9025c65f8701188903e11d6ed3f6f8e757f149b1a595152b6ca53d2a4ed9?context=explore) to the nodes.json & readme.

Still left v0.21.1 in there to have a "pre-taproot" version available.

### CODE REVIEW

**Comment by jamaljsr** [comment]
Thanks for the contribution. I did start working on this a while ago but got sidetracked and never circled back. I'll review this tomorrow. I think there may be more changes needed due to the new version not having two periods.

**Comment by cstenglein** [comment]
Tests are running now locally.

I don't know about the compatibility of `LND` with `bitcoind` v22.0, so just I set the compatibility of everything 0.21.1 to 22.0 for now. If that's not correct, just tell me :)

**Comment by cstenglein** [comment]
Tested it with `yarn:dev`: 
worked and downloaded the image correctly.

**Review by jamaljsr — APPROVED** [review]
I tested this branch locally and it works with all three LN implementations. I'm actually surprised this didn't require more changes to deal with the new version format. Apologies for taking so long to review, but thanks so much for the contribution. 👍

**Pull request merged**
